"""add source column to vocabulary_terms

Revision ID: fa8a61335426
Revises: 37b2d3c18a56
Create Date: 2026-05-07 01:51:53.328521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8a61335426'
down_revision: Union[str, Sequence[str], None] = '37b2d3c18a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary_terms', sa.Column('source', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vocabulary_terms_search'), 'vocabulary_terms', [sa.literal_column("to_tsvector('simple'::regconfig, term::text)")], unique=False, postgresql_using='gin')
    op.drop_column('vocabulary_terms', 'source')
    # ### end Alembic commands ###
